language: node_js
node_js:
- 7.5
cache:
- yarn
before_install:
- npm install -g snazzy
before_script:
- make semistandard
script:
- make test
- cat ./coverage-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js
